// test profile
// testing search strategy drag and drop weights
// Generated by Magic Lantern Profile Editor

const basePatterns = require('./base-patterns');

module.exports = {
  name: "test profile",
  description: "testing search strategy drag and drop weights",
  
  publications: {
    weights: {
      'variety': 1,
      'motion picture herald': 1,
      'the film daily': 1
},
    patterns: basePatterns
  },
  
  collections: {
    weights: {}
  },
  
  searchStrategies: {
    enabled: {},
    weights: {
      'exact_title': 1,
      'director_title': 1,
      'title_no_article': 0.8,
      'author_title': 0.5,
      'title_work_stoppage': 1
}
  },
  
  dateRanges: {
    "high": {
        "before": 1,
        "after": 1
    },
    "medium": {
        "before": 2,
        "after": 2
    },
    "low": {
        "before": 3,
        "after": 3
    }
}
};